etternagame/etterna

- src/StepMania.cpp
PrintScreen now makes a screencap in the PNG format while Shift + PrintScreen makes a resized screencap to the JPEG format.
> Switch keyboard shortcuts for screencapping

- CMake/SetupFfmpeg.cmake
- src/newRageSoundReader_MP3.cpp
Remov the formatprobe(It was crashing randomly. Seems to work fine without it. It's commented)
Change the FFMPEG version of the submodule(Built on linux)
Change the remaining deprecated FFMPEG calls to supported ones(Specifically stream[i]->codec to get the codec context is now obtained from the codecparameters(stream[i]->codecpar) and allocated using the codec, which is loaded before the context(It used to need the context to load) also using codecparameters and decode_audio4 replaced with 2 functions)
Make the Seek and Read functions used by the format context defined by us that make the api use ragefile use a hiddenptr instead of a pointer to the ragefile(Since the RageReader stores a hiddenptr and not a pointer this makes more sense)
> MP3 FFMPEG 

- Themes/_fallback/Scripts/02 Branches.lua
- Remove all calls to `GAMESTATE:GetSmallestNumStagesLeftForAnyHumanPlayer()` since it doesn't exist anymore. 
- Remove all course related control flow and function calls.
Probably doesn't affect til death at all, but themes using _fallback's branches were stuck in limbo after ScreenEvaluation because of this.
> Clean up 02 Branches.lua in the _fallback theme.

- NoteSkins/dance/DivideByZero/NoteSkin.lua
- NoteSkins/dance/SubtractByZero/NoteSkin.lua
The noteskins are missing definitions for the UpLeft and UpRight notes. With this, the notes display properly in-game instead of showing crosses in the extra lanes.
> Fixed noteskins for Solo gameplay

- Themes/Til Death/BGAnimations/ScreenEvaluation decorations/default.lua
- Themes/Til Death/BGAnimations/offsetplot.lua
- Themes/Til Death/Languages/en.ini
- Themes/Til Death/Scripts/01 color_config.lua
- Themes/Til Death/Scripts/01 player_config.lua
- Themes/Til Death/Scripts/01 timing_windows_config.lua
- Themes/Til Death/Scripts/02 ThemePrefs.lua
- Themes/Til Death/Scripts/Scores.lua
- Themes/Til Death/Scripts/Texts.lua
- Themes/Til Death/metrics.ini
These should be added to the Scripts/01 timing_windows_config.lua file in order to work(there are a few examples there too). The previous judge rescorer at eval screen has also been moved to lua(so it's not disabled anymore) and a menu option for using the custom timing windows has been added into the player options menu.
Also added a command to reset the current displayed score to the original one, currently bound to MenuUp.
> Add custom timing windows eval screen rescoring

- src/StepMania.cpp
It is undefined behaviour to call MESSAGEMAN->Broadcast before initialization (compilers are free to compile away the null check on MessageMan.cpp:209, and in fact g++ does, leading to a SIGSEGV on startup).
> Init MESSAGEMAN earlier

- Themes/Til Death/BGAnimations/ScreenNetEvaluation decorations.lua
Net evaluation screen SSRs are broken (GetSkillsetSSR used to take a number and now takes a string so it doesnt work atm online)
> Fix net eval ssr (1 => "Overall")

- src/DownloadManager.cpp
- src/DownloadManager.h
Dont download packs already loaded (Check by name) and fix a crash for null download calls from lua (Store finished downloads in a new map)
Also add an ifndef to downloadmanager.cpp that makes VS not give random errors sometimes
> Downloadies

- Themes/Til Death/BGAnimations/ScreenSelectMusic decorations/wifeTwirl.lua
Fixes https://github.com/etternagame/etterna/issues/77
Havent tested very thoroughly (Only checked that exiting a pack doesnt show song info, changing steps on a song changes the info properly in the firt two tabs and same goes for changing song)
> Dont show song info if steps change right before moving into a pack

- CMake/DefineOptions.cmake
- StepmaniaCore.cmake
- src/CMakeLists.txt
- stepmania.nsi
The exe should now be called Etterna.exe and the project in VS Etterna instead of Stepmania
Only tested on windows
> Rename Stepmania to Etterna in project name, exe files and installer

- Themes/_fallback/Scripts/SimNSkinPreview.lua
An easy noteskin preview system.
We can use this to display noteskin elements mostly tap note to show players what the noteskins look like.
To add this on a screen for example ScreenPlayerOptions, add the file ScreenPlayerOptions Overlay.lua
and add the line LoadNSkinPreview("Get", "Down", "Tap Note", PLAYER_1); in the Def.ActorFrame{} to add the Simple NoteSkin Preview as an child.
I didnt add it myself to ScreenPlayerOptions because I didnt know how Nick wanted it.
includes SimChild (Simple Child Finder) which can get a type of child included in actorframes.
> Simple Noteskin Preview System

- Themes/Til Death/BGAnimations/ScreenSelectMusic decorations/default.lua
- Themes/Til Death/BGAnimations/ScreenSelectMusic decorations/tabs.lua
- Themes/Til Death/BGAnimations/ScreenSelectMusic decorations/tags.lua
- Themes/Til Death/BGAnimations/ScreenSelectMusic decorations/wifeTwirl.lua
- Themes/Til Death/Scripts/01 tags.lua
- Themes/Til Death/Scripts/TabManager.lua
- src/MusicWheel.cpp
- src/MusicWheel.h
- src/Song.cpp
- src/Song.h
Allows the player to add tags to stepcharts (not songs), filter by them and removing them as well.
Usage example: https://puu.sh/zT2wH/c7f66103c1.webm
The tags are stored in such a way that allows easy sharing from player to player, since what it generates is a config file under `Save/Til Death_settings` called `tags.lua`, which contains a readable table with tags and their respective chart keys:
>  Add a player tag system to Til Death

- src/GameManager.cpp
via Nico's fix in 74516bb - tested that holds increase combo on Pump gametype and do not crash the client. Tested 5 different songs at various BPMs with successful results.
> pump holds appear to be working again

- Themes/Til Death/BGAnimations/_PlayerInfo.lua
changed the location of the logged in text at the bottom of the screen to above the session timer rather than to the right of it so it won't overlap
> Changed location of logged in text

- src/StepMania.cpp
For your consideration: It has been brought up from time to time to move or remove the service switch from the game because you can hit it in almost every menu and it sits next to the screenshot button. As a compromise (because the button has a legitimate use) I have simply added the requirement to hold Ctrl when pressing Scroll Lock to cause the "Service Switch" to be triggered. Thus, there is a much lower probability of hitting it in normal gameplay and when hitting the screenshot button.
The change can probably be done in a more efficient way. The boolean assigned that checks for Ctrl is actually equivalent to the one that checks later on for things like Ctrl+F4, etc. So it could probably be moved further up instead.
Regardless, this is a start.
> Rebind the Service Switch

- Themes/Til Death/BGAnimations/ScreenGameplay overlay/WifeJudgmentSpotting.lua
yikes
I didn't check to see if the function I removed was referenced anywhere else and this is what happens when you don't do that. This lua error probably breaks a lot of stuff and might need to be fixed asap.
Minor change; just commented the erroring code if we ever want to go back.
> Fix Lua Error Resulting From Restart Gameplay Button Change

- src/ScreenGameplay.cpp
The initial changes made to allow RestartGameplay to be remapped by bringing it into the game code opened up some more questions/problems that can be resolved. 
The first is that the previous behavior of the button when it was still in the theme allowed you to press the button when you were in the middle of failing (the screen is fading out and you are leaving the song).
This changes that so you can press it any time in gameplay. You aren't locked into failing a song when you fail it.
The second is that maybe we can start to have more control over the button's use. So I decided, although we haven't polished multiplayer completely, to force the button to only be usable offline. This also came about through some observations I made with using the button. If you use the button when in …
> Improve RestartGameplay Button Behavior

- src/GameManager.cpp
This was not fixed. They don't work properly. Turning this off will allow at least some kind of normal gameplay instead of having -severalthousand% scores. (remade pull request because reasons)
> Disable pump hold combo increases again

- Themes/Til Death/BGAnimations/ScreenGameplay overlay/WifeJudgmentSpotting.lua
- Themes/Til Death/BGAnimations/ScreenGameplay overlay/lanecover.lua
Previous behavior had the lane cover not really care at all where the notefield was.
I have changed it so that the lane cover now follows the notefield as it moves (and it saves). It doesn't care about vertical movement/transformation though, because it shouldn't make much of a difference.
I also added a little info about it on the Customize Gameplay text box if you have lane cover enabled.
This is my first attempt at theming something and it was basically a copy paste on existing code based on the behavior of ScreenGameplay underlay/ScreenFilter.lua so feel free to roast it
> Improve Lane Cover Behavior When Moving Notefield

- src/ScreenSelectMusic.cpp
Pressing p2 start in music select crashes the game for "no reason." Here's the reason. It's fixed (disabled).
Fixes #236 basically.
> Fix Player 2 Start Button Crash

- src/MusicWheel.cpp
So this should fix #230 
I'm not sure if exactly what has been done here is smart or correct. From what I can tell based on the reproduction steps for the bug, this should fix it.
The bug involves entering any non-single-style chart like solo or double and then exiting by any means. It will then filter every chart you have to that type. Only files that contain a diff with that style in it will appear.
It was seemingly narrowed down to only be happening whenever the user is logged in to smo/multiplayer.
So the steps to reproduce the bug are: Open the game, Open multiplayer, Log in to any game server (smo), Don't open a room or anything, just back out to the menu after logging in, Try any non single style chart and immediately leave the file. You should now only see compatible diffs.
I …
> Fix strange non-single filtering

- .gitignore
The temporary files created in this folder are created by Visual Studio 2015/2017 when you open a project with it, and are not ignored, which is problematic if you want to stash files/commit while having the project opened in Visual Studio. (for example :
> Adding Visual Studio 2015/2017 cache/options directory to the .gitignore

- Themes/Til Death/BGAnimations/ScreenGameplay overlay/WifeJudgmentSpotting.lua
This refers to vertical movement not being symmetrical when changing between upscroll and reverse.
This fixes that. Refer to issue #187 
I assume this mostly fixes or improves on the issue.
> Improve notefield movement behavior in customize gameplay

- src/NoteTypes.h
- src/Player.cpp
- src/PlayerAI.cpp
- src/PlayerAI.h
- src/ScreenEvaluation.cpp
- src/ScreenGameplay.cpp
New functionality: Holds and Rolls now drop. Since we don't keep track of actual taps (ghost taps, etc) the holds just drop instantly precisely when they drop in gameplay and we can't simulate the random tapping of rolls or holds. Along with this, the drops score correctly.
Mines should now work correctly. They don't bias to the left. Probably. I tested this once.
Rolls don't count as a bunch of 0ms marvs.
Also it was reported that play time, notes hit, and number of plays increased when viewing replays. That should be fixed, too.
Replays have yet to be tested on anything other than single 4k. It would be nice to see them work there.
This format is incompatible with old (non-column recording) replays. This shouldn't require too much work to make it happen, but in its current state it will …
> Improve Replay Behavior

- src/HighScore.cpp
- src/PlayerAI.cpp
This should allow you to load any older replay and view it like normal, assuming the score exists within your Etterna.xml as well as existing in your /Replays/ folder. If you can view the graph, you can view the replay.
There is a catch to how this works, though. Since old replays do not save data about dropped holds, note types, mines, or columns, some compromises had to be made. But really, the replays look almost identical.
Any hold/roll that is tapped is viewed in the replay as fully held, and never drops.
Mines are very rarely hit, if ever.
Simultaneous notes are judged in a seemingly random order instead of by column. Due to chord cohesion, you may end up with different judgements on the notes that make up a simultaneous note (jump, hand, quad, etc). This should not affect the …
> Make replay viewer compatible with old (pre v0.60) replays

- Themes/Til Death/BGAnimations/superscoreboard.lua
- src/DownloadManager.cpp
- src/DownloadManager.h
Originally, only top scores were being shown. This means that nobody could have a score on the leaderboard twice. I added a toggle between top scores and all scores like how EO does it. The default behavior is exactly the same as before, where it only shows top scores. Clicking the top scores toggle changes it to all scores, allowing duplicate entries on the leaderboard.
This was done by moving the lines referenced in #237 to the Lua call. Now, the original function just builds the entire list of scores. This doesn't seem to change anything negatively.
Added 2 Lua functions to DLMAN: GetTopScoresOnlyFilter and ToggleTopScoresOnlyFilter.
Fixes #237 by proxy since the Lua was using the chopped up lists that were built before.
> Add Top Score/All Scores Toggle so it can perform like EO Leaderboards

- src/DownloadManager.cpp
This is being caused by a discrepancy between expected values when flipping between online and local in the profile section of the screen.
Local grades return score.grade, which is an enum like expected in most of the lua.
Online grades return score.grade, which is a string that doesnt match the table that is searched by getGradeColor() in 01 color_config.lua.
I have changed the value that gets pushed from DLMAN from a string to the actual grade enum so that the values are more correct.
I've tested this in most places that grades and grade colors get called. It appears this exact lua function is only called once anyways, so since it works in this screen I would expect it to work everywhere else.
This fixes #245
> Fix lua error in online profile scoreboard

- Themes/Til Death/BGAnimations/ScreenEvaluation decorations/default.lua
- Themes/Til Death/BGAnimations/ScreenSelectMusic decorations/score.lua
- src/DownloadManager.cpp
- src/GameManager.cpp
- src/GameManager.h
- src/HighScore.cpp
- src/NoteDataWithScoring.cpp
- src/Player.cpp
- src/PlayerAI.cpp
- src/ScreenEvaluation.cpp
- src/ScreenGameplay.cpp
- src/ScreenInstallOverlay.cpp
- src/ScreenSelectMusic.cpp
Replay features and fixes:
1. Judge counts are less wrong and misses wont overcount and kill you for no reason
2. Opening the eval screen and then doing literally anything doesn't crash anymore
3. Radar values aren't negative (or shouldn't be.)
4. Lifts work in replays. Osu support.
5. Rate display in eval screen and thus, bpm display in replay gameplay is fixed.
6. Rate resets back to what it was before entering a replay if it was different.
7. Replays try to load the modifiers you had set on the score. For some reason, cmod->xmod doesn't work. The modifiers should unload after the replay.
8. Moved buttons around in the score tab due to overlap on smaller aspect ratios.
Less buggy in general, I would say. Shuffle or Turn replays are going to be broken until we care enough to deal with …
> Fix and Improve a lot of Replay things; Fix some minor theme stuff

- src/NotesLoaderDWI.cpp
- src/SongManager.cpp
Experimental change that hasn't resulted in any major slowdown or new crashes it seems.
It was thought that this was the fix for a thread deadlock, but that seems to be yet another issue of threads, not DWI specific.
> Fix mismatched track assert crash loading DWI files

- Themes/Til Death/BGAnimations/ScreenAvatarSwitch in.lua
- Themes/Til Death/BGAnimations/_switchavatar.lua
- Themes/Til Death/metrics.ini
1. Simplify the use of metrics.ini for avatar switch.
2. Add an invisible "in" transition lua file
3. Add text that says you actually activated the avatar switcher
4. Remove the random black screen when starting avatar switcher
5. Music never stops
6. Very slightly optimize some logic
PARTIALLY improves #225
> Fix music stop on avatar change

- Themes/Til Death/BGAnimations/ScreenGameplay overlay/default.lua
- Themes/Til Death/BGAnimations/ScreenGameplay overlay/replayscrolling.lua
- Themes/_fallback/Scripts/09 SimNSkinPreview.lua
- src/Actor.cpp
- src/Player.cpp
- src/Player.h
- src/PlayerAI.cpp
- src/ScreenEvaluation.cpp
- src/ScreenGameplay.cpp
- src/ScreenGameplay.h
- src/ScreenSelectMusic.cpp
Added these to lua so that we can make it work out.
The buttons for this are bound to the game buttons.
Pause -> Insert Coin
Move forward -> Effect Up
Move backward -> Effect Down
Increase rate toggle -> Shift (hold)
Smaller increment toggle -> Ctrl (hold)
How to bookmark a position and jump to it:
1. Hold Alt
2. Press Effect Up to set a position
3. Press Effect Down to jump to a position
Also fixed a lua error in playeroptions
Also undid changing modifiers for replays until we get that working better
> Add scrolling to replays

- Themes/Til Death/Scripts/01 timing_windows_config.lua
change the osu! marvelous rating to 3, as the 3.2 is only the weighting in score, not the accuracy
> Update 01 timing_windows_config.lua

- Themes/Til Death/BGAnimations/ScreenTitleMenu underlay.lua
- Themes/Til Death/Graphics/ScreenTitleMenu scroll.lua
- Themes/Til Death/Scripts/01 color_config.lua
This adds a new category to the color config screen and allows elements to use getTitleColor() to assign a color from the new category. Highlighted text on menu scroll is now 'positive' instead of a static color.
The text on the left side has been adjusted to look nicer (more focus on Etterna, the game, rather than til death) and now uses 'positive' as the color.
> Made title menu elements color configurable

- src/HighScore.cpp
- src/PlayerAI.cpp
- src/PlayerAI.h
- src/PlayerStageStats.cpp
- src/ScreenGameplay.cpp
- src/ScreenSelectMusic.cpp
Fix inconsistent results when restarting the game and converting judges.
Fix incorrect hold replay data loading.
Fix incorrect radar value numbers.
> Misc. Replay & Eval Viewer Fixes

- Themes/Til Death/BGAnimations/ScreenGameplay overlay/WifeJudgmentSpotting.lua
- Themes/Til Death/BGAnimations/ScreenNetSelectMusic decorations/default.lua
- Themes/Til Death/BGAnimations/ScreenSelectMusic decorations/default.lua
- Themes/Til Death/BGAnimations/ScreenSelectMusic decorations/goaltracker.lua
- Themes/Til Death/BGAnimations/ScreenSelectMusic decorations/playlists.lua
- Themes/Til Death/BGAnimations/ScreenSelectMusic decorations/score.lua
- Themes/Til Death/BGAnimations/ScreenSelectMusic decorations/wifeTwirl.lua
- Themes/Til Death/BGAnimations/ScreenSystemLayer overlay/default.lua
- Themes/Til Death/BGAnimations/_chorddensitygraph.lua
- Themes/Til Death/BGAnimations/goaldisplay.lua
- Themes/Til Death/BGAnimations/packlistDisplay.lua
- Themes/Til Death/BGAnimations/superscoreboard.lua
- Themes/Til Death/Graphics/Player combo/default.lua
- Themes/Til Death/Graphics/Player judgment/default.lua
- Themes/Til Death/Graphics/StepsDisplayListRow frame.lua
- Themes/_fallback/Scripts/00 Utility.lua
- src/Actor.cpp
- src/Actor.h
- src/ActorFrame.cpp
adds c++ implementations of getTrueX, getTrueY, and isOver and a new getTrueZoom 
the internal isover correctly handled nested zooms/coordinates (but not rotations yet, though it should be easier to add now)
all custom local isovers inside scripts should be removed and fallback to the utility definition, which is now an alias
also added is a recursive visibility check IsVisible and most getvisible use has been supplanted in the theme
unexposed addchild from lua in favor of a fakeparent approach; all the new functions use a fakeparent > parent > nil wrapper to support it
> Mouseover refactor

- README.md
This is my ninth PR on this repository.
This PR removes the "Etterna" header from the `README.md`. It is redundant as the first word in the `README.md` is "Etterna", as is the name of the repo.
> Remove redundant header text

- CMake/Helpers/CPackSetup.cmake
This PR changes where the Etterna files are installed. Previously, the files were placed in
`C:\Games\Etterna <version>\Etterna\<ALL_GAME_FILES>`. Since that middle `Etterna` directory was unnecessary, it has been removed.
> CPack Hotfix - Install Directory

- src/Etterna/Models/Songs/SongPosition.cpp
thankfully this was extremely easy to test with autoplay
i don't really like the idea of having to grab music rate from gamestate every update cycle but it doesn't appear to have that much effect, and it would make more sense to me to prevent visual delay from being divided by rate in the first place but it's not immediately obvious how or why that would happen
> Fix https://github.com/etternagame/etterna/issues/485

- src/arch/InputHandler/InputHandler_DirectInput.cpp
- src/arch/InputHandler/InputHandler_DirectInput.h
- src/archutils/Win32/GraphicsWindow.cpp
No longer poll for a set amount of seconds/tries for device changes when using direct input (Windows only afaik), instead listen to the WM_DEVICECHANGE windows message and poll once when we get it.
> Fix https://github.com/etternagame/etterna/issues/537

- CMake/Helpers/CPackSetup.cmake
Due to the way Etterna interacts with the filesystem on Mac and Windows, different install directories are required for Etterna to properly find the necessary resources. This commit will change the install directories to be compatible with the hard-coded filesystem values which Etterna uses to access the filesystem.
> CPack Update

- CMake/Helpers/CPackSetup.cmake
Newly introduce variable `INSTALL_DIR` was not set on linux, breaking builds. It is now set.
> Fix unassigned variable on linux

- CMakeLists.txt
It's important to add the source files after these options have been set, since lines executed in the "OS Specific Initialization" section affect what specific source files are included in the compilation. This commit updates that order.
> Modify CMake order of operations

- Themes/Til Death/BGAnimations/ScreenEvaluation decorations/default.lua
This is my first pull request! I added an MA/PA ratio indicator in the evaluation screen and the Chord Cohesion message now only shows when Chord Cohesion is enabled (also, it is aligned to the rest of the text, contrary to how it was before)
That's what it looks like
> ScreenEvaluation: Tweak Chord Cohesion text and add MA/PA ratio indicator

- .changelog/Release_0-66-1.md
- CHANGELOG.md
- src/arch/Sound/RageSoundDriver_ALSA9_Software.cpp
- src/arch/Sound/RageSoundDriver_DSound_Software.cpp
It looks like clang-format added some spacing that completely broke the ALSA driver.
I fixed the spacing and disabled clang-format on the offending line.
> Fix ALSA-sw driver not loading

- src/arch/InputHandler/InputHandler_X11.cpp
- src/arch/InputHandler/InputHandler_X11.h
Fix for #642 .
Analogous to [this](https://github.com/stepmania/stepmania/pull/1702) pull request:
> The X11 XKeyEvent structure (and others) include a timestamp field, with 1ms resolution.
> This was previously ignored causing the input timestamps to be set to the middle of each frame.
> If the timestamps are passed through then the event timestamps are not coupled to the framerate and the polling issues are resolved.
> Preserve event timestamps in X11 input driver

- src/Etterna/Models/NoteLoaders/NotesLoaderSSC.cpp
Make sure that a `BPMS` was in the header after processing steps to prevent the calculated defaulting to 60 when `DisplayBpm` is calculated.
This is my first commit to a open source project any comments will be appreciated , Hope I can become a regular.
fixes #615
> Add song BPM check in NotesLoaderSSC

- src/Etterna/Actor/Base/BitmapText.cpp
- src/Etterna/Actor/Gameplay/ArrowEffects.cpp
- src/Etterna/Actor/Gameplay/Background.cpp
- src/Etterna/Actor/Gameplay/DancingCharacters.cpp
- src/Etterna/Actor/Gameplay/DancingCharacters.h
- src/Etterna/Actor/Gameplay/NoteField.cpp
- src/Etterna/Actor/Gameplay/Player.cpp
- src/Etterna/Actor/GameplayAndMenus/BGAnimationLayer.cpp
- src/Etterna/Screen/Network/ScreenNetSelectMusic.cpp
- src/Etterna/Screen/Others/ScreenExit.h
- src/Etterna/Singletons/GameState.cpp
- src/Etterna/Singletons/GameState.h
- src/Etterna/Singletons/InputQueue.h
- src/Etterna/Singletons/ThemeManager.cpp
- src/RageUtil/Misc/RageTimer.cpp
- src/RageUtil/Misc/RageTimer.h
- src/arch/ArchHooks/ArchHooks.h
- src/arch/ArchHooks/ArchHooks_MacOSX.mm
- src/arch/ArchHooks/ArchHooks_Unix.cpp
- src/arch/ArchHooks/ArchHooks_Unix.h
- src/arch/ArchHooks/ArchHooks_Win32Static.cpp
- src/arch/InputHandler/InputHandler_DirectInput.cpp
- src/arch/Sound/RageSoundDriver_ALSA9_Software.cpp
- src/arch/Sound/RageSoundDriver_WaveOut.cpp
- src/arch/Threads/Threads_Pthreads.cpp
- src/archutils/Win32/CrashHandlerNetworking.cpp
This is done with the hope of fixing some stutter, drift, or inconsistency issues.
More testing is needed, and I have no idea what I'm doing here. 
RageTimer hasn't been touched for many years, and it's looking a bit outdated (and with outdated comments). Some discussion may need to take place as for what to do with it exactly. What I've done to RageTimer here is change its internal time-keeping stuff with a std chrono duration to hopefully make things both more precise and more consistent. However, I don't know if that has actually done anything. All I do know is that it didn't break anything. (and for the things it did break, I fixed)
Some decisions I made in working on this (for example removing the bAccuracy parameter) are based on the fact that some of these comments and practices …
> Experimentally Rewrite RageTimer Implementation

- .changelog/Release_0-67.md
- CMake/Helpers/CMakeLinux.cmake
- CMakeLists.txt
- Themes/Til Death/BGAnimations/ScreenSelectMusic decorations/other.lua
- src/Etterna/Globals/StepMania.cpp
- src/Etterna/Singletons/CommandLineActions.cpp
- src/Etterna/Singletons/LuaManager.cpp
- src/Etterna/verstub.in.cpp
- src/archutils/Unix/CrashHandlerChild.cpp
- src/archutils/Win32/CrashHandlerChild.cpp
- src/ver.h
At some point during the CMake rewrite for 0.65, these disappeared and were not replaced. This resulted in blanks showing up all over the place and especially in crash logs.
Now, it should show the version (no extra work is needed, it is pulled from the project version) and the exact commit/tag the build is from. Date and Time are removed.
Found a little typo that didn't affect anything, and I fixed that too.
> Re-add Git Hash & Version Info Variables

- .changelog/Release_0-67.md
- CMake/Helpers/CPackSetup.cmake
We used to prepackage a shortcut to the program that sat in the main folder of the game because of reasons and then stopped doing that. People apparently didn't like that.
This also disables the section asking if you want to add Etterna to PATH (we dont need this yet).
This also changes the install directory to `Etterna` from `Etterna <version>`
> Change Windows CPack to use the old directory & generate the old shortcut

- Themes/_fallback/BGAnimations/ScreenTestInput underlay.lua
- Themes/_fallback/Languages/en.ini
Places `Hold 'Enter' to exit` near the bottom center of the screen, along with a transparent box behind the text to prevent overlapping
> Add exit tip to ScreenTestInput

- src/arch/LowLevelWindow/LowLevelWindow_X11.cpp
- src/arch/LowLevelWindow/LowLevelWindow_X11.h
The existing LowLevelWindow_X11 didn't listen for window destroy events, so the program wouldn't exit when the window was destroyed.
> Added X11 event handling to handle delete window event

- src/RageUtil/Utils/RageUtil.cpp
Here's another change that might maybe possibly fix the stack overflow bug. Apparently when I thought I fixed it I actually didn't because I wasn't paying attention. Rather than copy pasting the solution I made for ssprintf, I chose to stick with the C ways for the purpose of speed. If we switch to spdlog, this becomes entirely irrelevant, anyways... probably.
The function change from `_alloca` to `_malloca` should get it to use heap space after it passes a threshold of bytes, but it still has the potential to overflow before using the heap space (it uses the stack space until the threshold is reached). And it requires a free. I could put the buffer into some C++ pointer or whatever but that again would be reducing speed. Apparently we really want to be fast here, so I wanted to avoid …
> Improve RageUtil's vssprintf on Win32

- Docs/Building.md
When attempting to build Etterna from a clean macOS Catalina installation, I noticed some extra steps had to be taken outside what was listed in the build instructions.
- The necessity of YASM or NASM to build ffmpeg.
- The possibility that Xcode command line tools may not be properly configured in the path, and how to fix that.
The instructions have been updated to include those steps.
> Update macOS dependencies and build instructions.

- src/archutils/Win32/GraphicsWindow.cpp
the reason this was commented was because commenting didnt seem to break anything and the particular function commented out caused a huge amount of lag (several seconds) when entering the options menu on opengl
need to test
> Uncomment Win32 GraphicsWindow DisplaySpec Validation

- src/Etterna/Singletons/DownloadManager.cpp
- src/Etterna/Singletons/DownloadManager.h
- src/Etterna/Singletons/PrefsManager.h
Also add a bit more logging for failure scenarios, and try to avoid
marking failed scores as uploaded
@MinaciousGrace do you want to test this before it gets merged?
I did a small test by playing you suffer in 2 rates offline, then logging in, and it uploaded fine and I saw the progress bar.
> Reduce copying and code duplication in dlman score uploads

- Themes/Til Death/BGAnimations/_calcdisplay.lua
- src/Etterna/Globals/CMakeLists.txt
- src/Etterna/Globals/MinaCalc.cpp
- src/Etterna/Globals/MinaCalc.h
- src/Etterna/Globals/MinaCalcOld.cpp
- src/Etterna/Globals/MinaCalcOld.h
- src/Etterna/Models/Misc/GameConstantsAndTypes.cpp
- src/Etterna/Models/Misc/GameConstantsAndTypes.h
- src/Etterna/Models/Misc/NoteTypes.h
- src/Etterna/Models/NoteData/NoteData.cpp
- src/Etterna/Models/NoteData/NoteDataStructures.h
- src/Etterna/Models/StepsAndStyles/Steps.cpp
- src/Etterna/Models/StepsAndStyles/Steps.h
- src/Etterna/Singletons/SongManager.cpp
- src/RageUtil/Utils/RageUtil.h
calc:
- back to refactored calc after fixing most of the bugs and verifying output outside of normalizer removal is the same
- normalizers removed, this means mods are probably going to need to push up and down, not just down
- enum'd pattern mods and some other stuff for easy iteration and debug output
- completely rewrote the roll detection/ohjump detection; both are now sequential
- added some pattern mods with rough implementations that will probably be needed in the future, or maybe not and then they'd just be place holders for something else
- redid all the debug output to be done in one pass, it's much faster now
- general ratings not tuned yet
- added basic automated testing that needs more cases before its really that useful, but the support is there and can be expanded to psuedo …
> rework calc/calcdisplay structure (calc version 273)

- src/Etterna/Globals/MinaCalc.cpp
- src/Etterna/Globals/MinaCalc.h
This pull request moves the row iteration loops out of the three above-mentioned functions into a single new function `Calc::gen_jump_hand_chord_data`. That function generates all the data which the three ~~downscalers~~ modifiers (?) need to function. It stores that data in a new struct called `JumpHandChordData`.
> Bundle row-iteration loops of SetHSMod, SetJumpMod, SetCJMod

- src/arch/Threads/Threads_Pthreads.cpp
Due to previous changes to RageTimer, a macOS thread wait function calculated the time incorrectly. This PR fixes #719, the black screen issue when loading the game screen.
> Fix #718 - macOS black screen

- .github/workflows/coverity-scan.yml
Libraries needed to build game are being installed by the CI.
> Fix Github Action for Coverity Scan 

- src/Etterna/Actor/Menus/MusicWheel.cpp
- src/Etterna/Models/Songs/Song.cpp
- src/Etterna/Models/Songs/Song.h
This refactor accomplishes many things:
1) Filter logic has been cleaned up and duplicate code has been condensed.
This should make it significantly easier to modify filter logic in the future to fix issues.
2) Highest Skillset should now work as intended with filters.
Earlier, there were two issues. First, in the old code, the continue statement after  
after checking if a given skill was the highest in a chart would continue the ratemod loop, not the skillset loop.
Secondly, in `Song::IsSkillsetHighestOfAnySteps`,
"Overall" was included as a result, which would always (naturally) be the highest. 
By setting a boolean flag inside the function to exclude "Overall" as an option in a sub-function, 'Highest Overall' now works as intended.
(Prior, 'Highest Overall' only worked if "Overall" …
> Refactor MusicWheel::FilterBySkillsets to fix several bugs and make it easier to mantain in the future

- src/Etterna/Actor/Menus/MusicWheel.cpp
- src/Etterna/Models/Songs/Song.cpp
- src/Etterna/Models/Songs/Song.h
- src/Etterna/Models/Songs/SongUtil.cpp
The function that found the highest MSD of a given skillset across the charts of a song incorrectly looked at charts from different game modes than the current one. This could lead to songs being incorrectly placed too high relative to others.
This PR modifies that function to make it return the highest MSD only from within the current game mode's chart types.
Close: #801
> Fix minor bug when sorting songs by skillset or overall MSD (Fix: 801)

- src/Etterna/Models/Songs/Song.cpp
- src/Etterna/Models/Songs/Song.h
Earlier, highest-only mode would allow songs that had a particular skillset
as the highest in any of its charts to be included, even if the chart
that did so did not meet other filter criteria.
This commit changes the IsSkillsetHighestOfAnySteps function into a new
IsSkillsetHighestOfChart function, which takes in a Steps* as a parameter.
> Make Highest-Only mode work correctly in filters

- src/RageUtil/Sound/RageSound.cpp
- src/RageUtil/Sound/RageSound.h
Fixes https://github.com/etternagame/etterna/issues/832
> fix mufft crash caused by unaligned input buffer

- src/Etterna/Models/Misc/PlayerAI.cpp
I don't know why this crash happens, but I can consistently trigger it by pressing "up" on the evaluation screen. This patch at least fixes the crash, if not the underlying root cause.
(I suspect there's something more deeply wrong with my game -- it refuses to save any replay files, which I suspect is related.)
> Fix a crash dereferencing m_ReplaySnapshotMap.rbegin()

- Themes/Til Death/BGAnimations/ScreenSelectMusic decorations/stepsdisplay.lua
- src/Etterna/Actor/Menus/MusicWheel.cpp
- src/Etterna/Models/Misc/PlayerState.h
- src/Etterna/Models/Songs/Song.cpp
- src/Etterna/Models/Songs/Song.h
- src/Etterna/Models/Songs/SongUtil.cpp
- src/Etterna/Singletons/FilterManager.cpp
- src/Etterna/Singletons/FilterManager.h
Earlier, Song:GetChartsOfCurrentGameMode() was used instead, which had two effects
1) Charts were not hidden when a filter was set
2) Bad glitchy things happened because it was referencing charts that were hidden on the C++ side.
This PR changes the Lua behavior to be as intended.
Note: The PR is based upon #864.
> Make new Lua binding Song:GetChartsMatchingFilter() that returns charts in current game mode matching filter

- src/Etterna/Actor/Menus/MusicWheel.cpp
- src/Etterna/Models/Misc/PlayerState.h
- src/Etterna/Models/Songs/SongUtil.cpp
- src/Etterna/Singletons/FilterManager.cpp
- src/Etterna/Singletons/FilterManager.h
`FILTERMAN->m_pPlayerState->wtFFF` was changed into `FILTERMAN->MinFilterRate`
There was no reason for the minimum filter rate to be within m_pPlayerState instead of FILTERMAN directly. 
MinFilterRate has been changed to function exactly the same as MaxFilterRate currently does.
> Refactor variable name and location for minimum filter rate

- src/Etterna/Models/Misc/GameCommand.cpp
- src/Etterna/Models/Misc/Profile.cpp
- src/Etterna/Models/NoteData/NoteDataWithScoring.cpp
- src/Etterna/Singletons/DownloadManager.cpp
- src/Etterna/Singletons/GameManager.cpp
- src/RageUtil/Utils/RageUtil.cpp
- src/RageUtil/Utils/RageUtil.h
- src/arch/Sound/RageSoundDriver_AU.cpp
The following changes were made:
Parenthesis were placed around some logical operators to remove warnings about implicit ordering.
Pragmas were placed to explicitly suppress warnings about non-literal format strings within `ssprintf`.
An incorrect format specifier was fixed within the `WERROR` macro.
An enum value that had been "added" to a string was changed to actually be appended.
This drastically reduces the number of warnings on my machine (100+ into ~15), and should generally make building information significantly more useful, as well as allowing important warnings to be seen.
> Fix several compile-time warning messages to make build output more useful

- Themes/Til Death/BGAnimations/ScreenSelectMusic decorations/tags.lua
I found a couple of bugs/inconveniences/bad code that cropped up with my exclude tags features.
*Makes songs reselect on tag change
*Makes local variables be local in RefreshTagsMessageCommand
*Makes the previous GUI associated that didn't work with 4:3 resolution now work with 16:9 and 4:3 resolution (and theoretically any resolution that ends up supported because it's based on frameWidth now)
> Exclude tags fixes

- src/Etterna/MinaCalc/MinaCalc.cpp
- src/Etterna/MinaCalc/MinaCalc.h
- src/Etterna/MinaCalc/UlbuAcolytes.h
- src/Etterna/Singletons/LuaManager.cpp
Due to a change in MSVC 16.7 it appears that static arrays of a large size take a simply unacceptable amount of RAM/heap to compile. This kills GHA as well as almost our local machines. This is a change that "fixes" the issue by removing the very large static arrays.
Although this behavior may be due to a real MSVC bug, this change is useful on its own to allow a somewhat greater range of files. But still, the difference between 40k intervals and 100k intervals for a max size is basically nothing in the grand scheme of files available. Most files fall within 500-1000 intervals (4-8 minutes).
Merge AFTER #883
> Switch static array to vector for interval based MinaCalc containers

- src/Etterna/MinaCalc/MinaCalc.cpp
I profiled both the new and old calc to compare performance by deleting cache.db and timing from game-start to the first time I saw the menu screen using XCode's Instruments tool.
|Measurement|Old Calc | New Calc|
|---|---|---|
|Relative Chisel weight to total execution time|12%|10%|
|Total CPU-seconds spent in Chisel<br>(Slighty unreliable metric)|58.36|46.45|
|Total run time (CPU-Mins)<br>(Highly unreliable metric)|8.08|7.67|
Although this improvement is small, the new code is cleaner and easier to understand than the old code was, making this a change with no downsides.
There was zero difference in calculated values between the old calc and the new one with my changes, using the Calc test xml.
Related to #881 -- the first iteration is unimproved, but the 2nd-7th should take 50% less …
> Refactor MinaCalc's Chisel function to improve performance

- src/Etterna/Models/Songs/Song.cpp
Earlier, a bug was caused where "Overall" and other skillset sorts would be
incorrect, as the sort would find the highest MSD chart of *any* from the
current game mode, even those hidden by the filter. This lead to confusing
behavior.
This fix simply replaces the GetChartsOfCurrentGameMode call with a
GetChartsMatchingFilter. (Which falls through to the above if the filter is
not set)
Note: I only made a one-line change in Song::HighestMSDOfSkillset.
The rest is clang-format stuff, since it apparently has not been run after the logger changes.
> Fix broken skillset sort when filter applied

- src/Etterna/MinaCalc/MinaCalc.cpp
- src/Etterna/MinaCalc/UlbuAcolytes.h
This PR does small two things:
1) Implement a suggestion from one of mina's comments in the calc. This makes the calc slightly faster than v263 was on average. 
Basically, it's possible to avoid a lot of work by only chiseling on skillsets that actually effect the result of the final `AggregateRatings`. 
This _does_ change the output slightly, but 98.7% of the charts on my machine (~20k) produce the exact same overall value (bit-exact). Only 20 files increased in rating, the rest went lower. Here's the 20 largest changes:
```
01 -0.48      Road of Death (Edit)                           X8a1a1fc7a55986e2397791da4936097283cefc55
02 -0.36      Pandemonic Hyperblast (Challenge)              X28bdf6d15e3ad299ba97847625b1de9d517f45e3
03 -0.20      Nightmare (Challenge) …
```
> MinaCalc Profilemancy

- src/Etterna/MinaCalc/Dependent/HD_Sequencers/GenericSequencing.h
- src/Etterna/MinaCalc/MinaCalc.cpp
- src/Etterna/MinaCalc/PatternModHelpers.h
- src/Etterna/MinaCalc/UlbuAcolytes.h
a
There is a lot to say about this PR but mostly you should just pull it and have a look. This substantially reduces overrated jackspeed outliers but is still pretty accurate on actual for real definitely-jackspeed files, at least going by mina's CalcTestList.xml and from what I can tell from my own profile. Non-jackspeed files are not changed. I think this change is pretty good, but I'm pretty ignorant about high level difficulty, and it might be that you don't want to use it and instead use my tooling to find a better set of changes.
I do make a change to how the jack_diff array is computed, this was necessary to preserve proper scaling with rates in certain situations. This is basically an inelegant hack to cover for the fact there are no jackspeed pattern mods.
Now, the good stuff: I …
> Unsolicited proof-of-concept machine learning jackspeed PR  

- Themes/Til Death/BGAnimations/ScreenSelectMusic decorations/wifeTwirl.lua
- Themes/Til Death/BGAnimations/goaldisplay.lua
- src/Etterna/Models/Misc/Profile.cpp
Currently it goes from 99->99.75->99.97->100
This PR should also fix a bug when bringing a goal down from a number higher than 99 causing a different view to show (previous percentage - 1)
This PR should also expand the profile goals percentages and the screen select goals percentages decimal counts to 3 when necessary to hold 4A or 5A goals.
> Make profile goals go from 99->AAA->4A->5A

- CMake/Modules/FindDirectX.cmake
Currently it checks PATH first then checks all the locations where DX is commonly found, with this PR it will check all the locations DX is commonly found, then if it isn't found will check PATH.
> Make CMake check in specific directories before defaulting to PATH for DirectX

- src/Etterna/Models/NoteLoaders/NotesLoaderOSU.cpp
Extremely small BPM values being passed into the OSU loader could cause
Etterna to crash by making stof go out of range by passing a value in too
small to be representable by a float.
This change sidesteps this issue by instead using stod, and allowing the
result to be truncated to a float (truncating unrepresantable values to 0).
This can still technically crash, but you'd need to pass in even more
ludicrously small values to do so.
In the future, it might make sense to wrap this in a try-catch block and
catch the std::out-of-range exception to continue cleanly.
Note: I'm leaving this draft for now to let someone more knowledgeable than me make sure it's ok.
Notably, the second value can be exactly 0; I don't know if that's potentially harmful. 
I tried playing a file that previously …
> Replace stof with stod (truncating result to float) to prevent low-value crash

- src/Etterna/Models/Songs/Song.cpp
- src/Etterna/Models/Songs/Song.h
- src/Etterna/Models/Songs/SongUtil.cpp
This was caused by a previous change which made HighestMSDOfSkillset only consider filter-matching charts, in order to fix sorting by skillset difficulties.
This had the side effect of breaking the filter option of highest difficulty only, which also used the same function.
This commit fixes the issue by adding in a boolean flag to HighestMSDOfSkillset, which toggles between considering filtered charts and charts of the current game mode.
> Avoid stack overflow caused by ChartMatchesFilter calling HighestMSDOfSkillset which called ChartMatchesFilter itself

- src/Core/Platform/PlatformMac.mm
This replaces the earlier broken way with the correct Objective-C way to do it.
Note: I'm not familiar with Objective C, and this solution was created with 15 mins of googling.
It's possible that there's some subtle mistake I'm missing here.
It does work properly with odd UTF filenames including non-ascii characters from my limited testing.
> Fix macOS platform function openFolder

- src/Etterna/Actor/Menus/MusicWheel.cpp
- src/Etterna/Models/Songs/Song.cpp
- src/Etterna/Models/Songs/SongUtil.cpp
- src/Etterna/Singletons/FilterManager.cpp
- src/Etterna/Singletons/FilterManager.h
This adds in a new filter option -- a clear % range.
Charts are only matched in the filter if the player's best score percent on a chart falls between the lower and upper bounds.
This also respects the SSRNormSort option -- if it is enabled, that clear % is used, if it is disabled, the % of the judge used when the song was played is used instead.
This also introduces a small filter change -- certain filter options (currently duration and clear %) must be matched, even in a non-exclusive filter.
This is done because no-one wants to filter for "Charts that are (between 21-23 JS), (between 20-22 HS), or (have been cleared with at least 60%)", they want "Charts that are ((between 21-23 JS) or (between 20-22 HS)) *and* (have been cleared with at least 60%)".
The easiest way to test this new …
> Add C++ Backend For New Filter Option -- Chart Clear %

- src/Etterna/Singletons/DownloadManager.cpp
In the JSON returned by the API, "errors" is an array, not an object: this lead to a failed assert in the d["errors"].HasMember() call.
I got this crash while loging in, as a new user with no score on etternaonline, this probably affects every new user.
The handling of API returned "errors" is inconsistent in the download manager at this point, this should probably get worked on in the future.
> Fix 404 error parsing of top/25 API answer

- CMakeLists.txt
This allows for security updates related to OpenSSL to come faster for Unix systems that have dynamically linked OpenSSL as well as allowing building on Unix systems that do not have statically linked OpenSSL.
> Change OpenSSL to dynamically link when not on windows

- src/Core/Platform/PlatformMac.mm
This is a quick and dirty way to do this.
A better way to do it would be along the lines of 
```
bool isOtherInstanceRunning(int argc, char** argv){
if([[NSRunningApplication runningApplicationsWithBundleIdentifier:[[NSBundle mainBundle] bundleIdentifier]] count] > 1){
//If macOS has another application currently running with the same bundle identifier, it must be another Etterna instance. 
return true;
}
return false;
}
```
However, the way we build Etterna on macOS makes it not actually have a bundle identifier, which makes the above approach impossible.
> Implement isOtherInstanceRunning for macOS platform

- src/Etterna/Models/Songs/SongUtil.cpp
The old length sort grabbed the longest song from *all* charts of a song.
This fix changes that to only look at the longest song which matches the filter (and thus the game mode)
> Fix incorrect LENGTH sort when filters are applied

- Themes/Til Death/BGAnimations/ScreenSelectMusic overlay/currentsort.lua
- Themes/_fallback/Languages/en.ini
- Themes/_fallback/metrics.ini
- src/Etterna/Actor/Menus/MusicWheel.cpp
- src/Etterna/Models/Misc/GameConstantsAndTypes.cpp
- src/Etterna/Models/Misc/GameConstantsAndTypes.h
- src/Etterna/Models/Songs/SongUtil.cpp
The Ungrouped sort sorts song by title, placing every song into a single group.
This is mainly intended to be used with filters and/or playlists.
TODO: Add non-English translations for new Ungrouped Sort Mode text.
> Add new sort mode -- Ungrouped

- Docs/Building.md
build-essential contains dev build tools like gcc, g++ & make. I see a couple people getting confused on why etterna fails to build when they don't have a compiler or cmake, this would resolve that problem
> Add build-essential to debian dependencies

- src/Core/Misc/PlogLogger.cpp
- src/Core/Platform/PlatformMac.mm
Apple introduced app translocation in macOS Sierra v10.12, which prevents apps from accessing files outside their own .app directory (via a relative reference). This is a problem for Etterna since all files are accessed with relative references to where the .app directory is located. Apple moves the app to a secure location, then attempts to run the program. Etterna fails right away as it requires those local files. The code in init() will load Apple's private security API, load the functions, and call on them to untranslocate by removing the quarantine restriction on the original binary location. Apple will not accept the app into their app store unless this code is removed.
> 🔑 macOS Auto-Untranslocation

- src/Etterna/Globals/StepMania.cpp
The ALSA-sw driver needs to be able to access /proc/asound in order to work. This was previously done by mounting / as /rootfs and then accessing "/rootfs/proc/asound".
Ex:
https://github.com/etternagame/etterna/blob/021eae5f9ffe1a0c9edf3003c129b48ac636cf6c/src/arch/Sound/ALSA9Dynamic.cpp#L34
In 52dcd2c769dd2b6780f0f210360a8ac33a2c6334, the /rootfs mount was removed, which broke all linux audio.
In this pr, I put the /rootfs mount back as close as I could to where it was before - but the code structure has changed enough that there may be a better place for it.
> Mount /rootfs so linux audio drivers work

- src/Core/Platform/PlatformUnix.cpp
This fixes some shell errors, for example when there is an apostrophe (`sh: 1: Syntax error: Unterminated quoted string.`) or a parenthesis (`sh: 1: Syntax error: "(" unexpected`) in the URL.
> Platform Unix: escape the URL passed to xdg-open

- src/Etterna/Actor/Gameplay/NoteDisplay.cpp
- src/Etterna/Actor/Menus/MusicWheel.cpp
- src/Etterna/Actor/Menus/OptionRow.cpp
- src/Etterna/FileTypes/XmlFile.h
- src/Etterna/Models/CMakeLists.txt
- src/Etterna/Models/Lua/LuaBinding.cpp
- src/Etterna/Models/Lua/LuaBinding.h
- src/Etterna/Models/Misc/CubicSpline.cpp
- src/Etterna/Models/Misc/DBProfile.cpp
- src/Etterna/Models/Misc/DBProfile.h
- src/Etterna/Models/Misc/HighScore.cpp
- src/Etterna/Models/Misc/Profile.h
- src/Etterna/Models/Misc/TimingData.cpp
- src/Etterna/Models/Misc/TimingData.h
- src/Etterna/Models/NoteLoaders/NotesLoaderBMS.cpp
- src/Etterna/Models/NoteLoaders/NotesLoaderBMS.h
- src/Etterna/Models/NoteLoaders/NotesLoaderOSU.cpp
- src/Etterna/Models/NoteLoaders/NotesLoaderOSU.h
- src/Etterna/Singletons/MessageManager.cpp
- src/Etterna/Singletons/MessageManager.h
There are still two warnings about a no-discard function return values being discarded and like 50 `undefined-var-template` warnings about 3 static members: `EnumTraits<Type>::Invalid`, `EnumTraits<Type>::szName`, `Luna<Type>::m_sClassName`.
> Fix more clang's compile-time warnings

- .github/workflows/ci-workflow.yml
- CMake/Helpers/CMakeMacOS.cmake
- CMakeLists.txt
- Update macOS CI to have OS name label. Attempted to add macOS Big Sur, but Github doesn't currently allow them for public use.
- Link OpenSSL statically on binary on macOS.
> 🔨 Update macOS Build and CI

- src/Etterna/Models/Songs/Song.cpp
Both Length and Clear% must always be matched, even in non-exlusive mode.
However, this has the effect of non-exlusive mode just becoming any chart
that matches either of those ranges, regardless of skillsets.
This changes them to require a skillset to be matched if any are set; if
no skillset ranges are set, a non-exclusive filter using only length/clear%
behaves identically to an exclusive one.
> Fix bug with non-exclusive filters and required Length/Clear% ranges

- src/RageUtil/Sound/RageSound.cpp
Etterna used to randomly crash in the chart select screen every few days for me. The crash originated in the music visualizer code, and Nick12 managed to find a fix which seems to work ([Discord link](https://discord.com/channels/261758887152058368/261811430888570880/871028424674770944))
> Fix visualizer crash

- CMakeLists.txt
- src/Etterna/CMakeLists.txt
This commit **should** allow using Etterna's CMake structures externally for projects that depend on certain library-like functionalities within Etterna like NoteLoader or MinaCalc without removing the ability to build or functionalities of the CMakeLists altered.
The CI passes, however I have only tested this change in linux
> Make external builds not break from local CMakeLists

- CMake/Modules/MacOSXBundleInfo.plist.in
Etterna (currently) doesn't support high resolution displays, so this commit
adds a property to the macOS generated plist that tells macOS we don't
Credit to @jameskr97 for the fix.
(Before this PR)
> Implement fix for Etterna showing at quarter scale on macOS sometimes

- Docs/Building.md
I built the game on alpine earlier and these were the dependency names I needed for it's package manager (apk). Idk if it makes sense to add a (presumably) niche usecase like that to the instructions
> Add alpine dependencies to Building.md

- Themes/Til Death/BGAnimations/ScreenGameplay overlay/leaderboard.lua
The entries in question are highlighted in green here:
I tested this in a local multi server and with the EO leaderboard, seemed to work fine
> Fix buggy multi leaderboard entries

- src/Core/Platform/PlatformMac.mm
Previously, if the translocation functions in Security.framework could not be found, we just crashed by trying to call a nullptr.
Now, if dlsym or dlopen fails for any reason, we instead log a message and skip the translocation checks.
This should (?) make Etterna compatible with macOS High Sierra again.
> Handle case where translocation API functions are unavailable on old macOS versions

- src/Etterna/Singletons/ThemeManager.cpp
Should fix
https://crash.etterna.dev/crash-reports/d48f8d83-6089-400b-b649-b426c4f058d6
In
https://github.com/etternagame/etterna/commit/74618a164f623f5e37174cd8f0927ad7ea87b07a#diff-fa2cfd199eddea90ff3e3cad44b343d951a77386b267c89d39b689c07a534e65R652
mina changed a couple string types to string&, per a resharper
suggestion
Doing that causes some crashes, the comment above the lines this commit
changes explain that ReloadMetrics can delete/reallocate the string
parameters the functions take by reference, so they make a local copy of
their string parameters. This can result in a crash if a lua script
error is encountered and we attempt to reloadmetrics and retry, for
example here
https://github.com/etternagame/etterna/blob/201115635bb3635ca5f3e65c395e55ba7c1b5300/src/Etterna/Singletons/Them …
> Fix ThemeManager::GetPathInfoToRaw crash

- src/RageUtil/Misc/RageThreads.cpp
- src/RageUtil/Sound/RageSound.cpp
- src/RageUtil/Sound/RageSound.h
Example of the bug: https://crash.etterna.dev/crash-reports/aa1d672c-2eb7-459a-8e05-cc4685b3c6cd
The music thread can lock `g_Mutex` and then `recentSamplesMutex`:
And the main thread can lock those 2 mutexes in the opposite order: 
The reason for the weird error message is that our mutex impl on windows tries to detect deadlocks with a 15 second waiting time:
https://github.com/etternagame/etterna/blob/201115635bb3635ca5f3e65c395e55ba7c1b5300/src/arch/Threads/Threads_Win32.cpp#L231-L250
And this return value of false is checked here: https://github.com/etternagame/etterna/blob/201115635bb3635ca5f3e65c395e55ba7c1b5300/src/RageUtil/Misc/RageThreads.cpp#L471
but the crash was commented when we moved to crashpad in https://github.com/etternagame/etterna/commit/1d8deb8dfad4681e281dde2e315623f0 …
> Fix audio callback deadlock

- src/RageUtil/Graphics/RageDisplay_D3D.cpp
Fixes #953
Like I mentioned in https://github.com/etternagame/etterna/issues/1166
The ::Reset documentation https://docs.microsoft.com/en-us/windows/win32/api/d3d9helper/nf-d3d9helper-idirect3ddevice9-reset says:
> Before calling the IDirect3DDevice9::Reset method for a device, an application should release any explicit render targets, depth stencil surfaces, additional swap chains, state blocks, and D3DPOOL_DEFAULT resources associated with the device.
Looking around the only place where we call `->Reset`, it seems we are deleting render targets *after* calling Reset, instead of before:
https://github.com/etternagame/etterna/blob/201115635bb3635ca5f3e65c395e55ba7c1b5300/src/RageUtil/Graphics/RageDisplay_D3D.cpp#L403-L417
> Delete d3d render targets before Reset()ing Device

- src/RageUtil/Graphics/RageDisplay_D3D.cpp
dxerr.h was deprecated by microsoft, so we stopped using it in https://github.com/etternagame/etterna/commit/cae27008098c6ceea0c85b8f344f679f81a79a92 , and replaced our usage of `DXGetErrorString` with a hardcoded empty string. This replaces that with an MIT licensed `DXGetErrorString` implementation, trimmed down to just d3d9 which is what we need.
With this, d3d errors should report the error string.
> Slightly improve RageDisplay_D3D error reporting

- Docs/Building.md
Although there's multiple instances of "doxygen" not being capitalized, those are the actual capitalization for the directories and packages. This commit fixes instances where it *isn't* used in the context of a package or directory
> Capitalized "doxygen" in Building.md

- README.md
In this commit, I capitalized 3 instances of "GitHub" being written as "Github" or "github". "GitHub" is the correct capitalization.
> Capitalize "GitHub" correctly in README.md

- src/Etterna/Models/Misc/EnumHelper.h
These warnings are only indicating that a linker error might occur later ... which it doesn't.
The specific warnings are caused by us instantiating the various EnumTraits static member variables in a different translation unit than the one building Check() and friends.
However, as we *do* instantiate them, the warning isn't helpful and just spits out a lot of noise into our build output.
> Suppress a whole lot of EnumTraits warnings

- src/Etterna/MinaCalc/CalcWindow.h
- src/Etterna/MinaCalc/Dependent/HD_PatternMods/Chaos.h
- src/Etterna/MinaCalc/Dependent/HD_PatternMods/WideRangeRoll.h
- src/Etterna/MinaCalc/MinaCalc.cpp
- src/Etterna/MinaCalc/SequencingHelpers.h
- src/Etterna/MinaCalc/UlbuAcolytes.h
The calc is unusually sensitive to tiny changes in row times. For example depending on whether they are computed [here](https://github.com/etternagame/etterna/blob/877d46ae88f9d7d6c887a7e954192bd757399cc1/src/Etterna/Models/Misc/TimingData.cpp#L1400) or [here](https://github.com/etternagame/etterna/blob/877d46ae88f9d7d6c887a7e954192bd757399cc1/src/Etterna/Models/Misc/TimingData.cpp#L1418) can cause a large change in the result, even when they are equivalent (i.e., bpm change after the last non-empty row)
This is kinda academic but it seemed like an interesting thing to track down and fix so here we are. This PR moves most files around randomly in a range of around 0.5 MSD. It is apparently a bit better on average but that may just be chance
It turns out there were 2 sources of …
> Some calc floating point stability fixes 

- src/archutils/CMakeLists.txt
- src/archutils/Win32/Etterna.manifest
This fixes files with mojibake path errors on newer versions of Windows.
According to https://learn.microsoft.com/en-us/windows/apps/design/globalizing/use-utf8-code-page on old versions prior to 2019, things will work as before.
Maybe this will uncover mysterious latent bugs but since Linux and MacOS do in fact work it seems unlikely to me!?
> Add Windows UTF8 Manifest

- src/RageUtil/Sound/RageSoundPosMap.cpp
The `*this = cpy` statement calls the copy constructor, which does `delete m_pImpl` while the field is uninitialized. Just removing it should be fine, we allocate a copy of the m_pImpl anyways and that is the only field in the type.
> Fix uninit read Defect in SoundPosMap

- Themes/Rebirth/BGAnimations/ScreenSelectMusic decorations/curSongBox.lua
- Themes/Til Death/BGAnimations/ScreenSelectMusic decorations/wifeTwirl.lua
- Themes/bare-frames/BGAnimations/ScreenSelectMusic decorations/songinfo.lua
- src/Etterna/Actor/Menus/BPMDisplay.cpp
This fixes the remaining problem within #615 wherein the displayed BPM range for songs that had different BPM ranges per-chart was incorrect.
#619 fixed most of the problems, but as Poco noted in https://github.com/etternagame/etterna/pull/619#issuecomment-520270829 the Lua binding for BPMDisplay `SetFromSteps` still did not work even after that change.
That was because `BPMDisplay::SetBpmFromSteps` did all the work to determine the correct BPM range and then just ... didn't call `SetBPMRange` to actually update it.
This PR fixes that function and then makes the simple changes required to Rebirth, Til Death, and bare-frames to get them to use it.
Closes: #615
> Fix incorrect bpm display for ssc songs with varying bpms per-chart

- extern/CMakeLists.txt
Without this change, we run into the problem where our GHA builder has the libssh2 library installed (and so the built cURL dynamically links to it) but the average mac user does not, leading to the application immediately crashing on start.
This was already fixed once before, but with the recent(ish) upgrade to a newer version of cURL than what we'd been using in f1dd6fe, the option CMAKE_USE_LIBSSH2 was renamed to CURL_USE_LIBSSH2, which silently made our forcing of that setting to OFF no longer work.
> (Again) disable use of libssh2 when building cURL

- extern/CMakeLists.txt
- extern/websocketpp/CMakeLists.txt
- extern/websocketpp/Doxyfile
- extern/websocketpp/changelog.md
- extern/websocketpp/cmake/CMakeHelpers.cmake
- extern/websocketpp/docs/faq.dox
- extern/websocketpp/examples/print_client_tls/print_client_tls.cpp
- extern/websocketpp/readme.md
- extern/websocketpp/websocketpp/endpoint.hpp
- extern/websocketpp/websocketpp/logger/basic.hpp
- extern/websocketpp/websocketpp/roles/server_endpoint.hpp
- extern/websocketpp/websocketpp/transport/asio/connection.hpp
- extern/websocketpp/websocketpp/transport/asio/endpoint.hpp
- extern/websocketpp/websocketpp/transport/asio/security/none.hpp
- extern/websocketpp/websocketpp/transport/asio/security/tls.hpp
- extern/websocketpp/websocketpp/version.hpp
websocketpp dependency uses template specialization on class constructors which isn't allowed in c++20, this change fixes that
> Fix websocketpp to be compliant with c++20

- .ci/generate_doc_configs.sh
- Docs/legacy/Themerdocs/pause_menu.md
- Docs/legacy/Userdocs/Keymaps_ini_format.md
Exclude pause_menu and keymaps_ini_format from Etterna documentation sidebar
Amusingly enough the pause menu was probably the worst SM5 legacy documentation that could have shown up, since pausing is *definitely* not an Etterna feature :)
With this change, both are still *built* by Jekyll, and can be navigated to if you know the link, but won't be prominently displayed on the homepage.
Also
Install graphviz in Etterna Doc CI to properly build DOT files
> Minor Etterna Documentation Fixups (pause_menu.html exclusion & fixing images)

- Themes/Til Death/BGAnimations/ScreenEvaluation decorations/default.lua
f846fc05ea343fbaa380ace932236e16f9f8a5cb
Before these changes, The fill, percent, and count would use the wrong judge when selecting a score from the right-side leaderboard.
For example, if a score's judge is 5, and I change the judge on the evaluation screen to 6, then click on the same or a new score, the fill, count, and percent update using the score's judge instead of the set judge (6).
After these changes, this is no longer the case since the fill, count, and percent now use the judge you have selected.
ef3abb618d18f567504d29de77f2d0bc4086ec62
Before these changes, the left and right cb counts update using the score you entered the evaluation screen with when changing judges instead of the selected score, causing inaccurate values if you select a different score and change judges. …
> til death fix updating of judgement bar fill, percent, count, and left/right cbs

- Themes/Til Death/BGAnimations/ScreenPackDownloader underlay.lua
previously they'd be stuck as active until you moused over them
> Pack downloader search/filter inactive on init(til death)

- Themes/Rebirth/BGAnimations/playerInfoFrame/main.lua
Only changed this DeviceButtom_ since I didn't find any other one which could result in similar bugs. I wasn't able to test the bug because I don't a non-conventional layout keyboard but I'm pretty certain this should do the trick.
This is my first attempt in contributing to the project. If if mess anything up please tell me.
> Rebirth login binding change to not use physical location. Issue #1118

- CMake/Helpers/CPackSetup.cmake
- src/Etterna/Globals/StepMania.cpp
This PR is a first step towards addressing #651. It allows users (or package maintainers) to customize the Etterna virtual filesystem mounts using environment variables so that the game installation itself can remain immutable while any variable data is stored elsewhere. This is especially necessary for a NixOS release, as the Nix store is read-only.
More specifically, this PR does the following:
* Causes Etterna to check the env var `ETTERNA_ROOT_DIR` on startup. If present, its value is used for the path of the main mount; otherwise, the current behaviour is used, namely mounting the installation directory.
* Causes Etterna to check the env var `ETTERNA_ADDITIONAL_ROOT_DIRS` on startup. If present, it's parsed as a list of paths that are treated identically to the paths listed in the …
> Configurable virtual fs mounts based on environment variables

- Themes/_fallback/Scripts/02 Colors.lua
When you set the saturation of white (or any color with maximum value and minimum saturation), the color should still remain white because increasing the saturation should not have any effect unless the hue is defined and c.Value is less than 1.
Also cleaned up ColorToHSV as it was possible for s = -nan (division by zero)
This addresses ticket #1285
> Saturation fix

- src/Etterna/Models/NoteLoaders/NotesLoaderSM.cpp
- src/Etterna/Models/NoteLoaders/NotesLoaderSM.h
- src/Etterna/Models/NoteLoaders/NotesLoaderSMA.cpp
When I loaded a chart with bpms 170 -> 0 -> 170 in 0.70, the chart was treated as having a constant 170 bpm. To avoid timestamps going to infinity, we can treat 0 bpm segments as having the same bpm as the previous segment. Charts with `bpms.size > 1` will always have a previous segment to draw from.
Closes #946
> Set any 0 bpm segments to the previous segment's bpm

- src/Etterna/Screen/Others/ScreenSelectMusic.cpp
ScreenSelectMusic::OnConfirmSongDeletion() uses std::filesystem, which isn't supported with the macOS sdk we're currently using.
Rather than just completely failing to compile, do the marginally better action of emitting a compiler warning and making the function log a warning and do nothing else on macOS.
> Work around std::filesystem being unavailable on mac w/ warnings

- CMake/Helpers/CMakeMacOS.cmake
- CMake/Helpers/SetupFFMPEG.cmake
- CMakeLists.txt
- extern/CMakeLists.txt
- extern/sse2neon/CMakeLists.txt
- extern/sse2neon/README.txt
- extern/sse2neon/sse2neon/LICENSE
- extern/sse2neon/sse2neon/README.md
- extern/sse2neon/sse2neon/sse2neon.h
- src/Etterna/MinaCalc/PatternModHelpers.h
- src/Etterna/Models/Misc/StageStats.cpp
- src/Etterna/Screen/Others/ScreenSelectMusic.cpp
In 2020, Apple introduced their own ARM chip, the M1, which replaced the Intel x86_64 chips they had been using.
Consequently, all modern macs run on ARM processors and run ARM code.
Etterna has only been able to work on them because Apple provided Rosetta v2, a translation layer allowing our x86_64 mac builds to be dynamically JIT-d into ARM code, which can be run.
However, this JIT process has some overhead and produces less efficient code than code compiled for the target processor in the first place, and more importantly Rosetta v2 will have support dropped for it at some point in the future.
This PR allows Etterna to be built for Apple Silicon targets, and is an important first step in the process of automatically generating Apple-Silicon-compatible releases.
The other two major …
> Allow for native Apple M1 ARM builds!

- extern/crashpad/crashpad/third_party/mini_chromium/mini_chromium/base/logging.h
- extern/crashpad/crashpad/third_party/mini_chromium/mini_chromium/base/strings/utf_string_conversion_utils.h
For some reason, a dependency of crashpad seems to be just ...
missing a <stdint.h> include in an obvious way.
I don't know how it ever worked before, but this fixes it now :)
> Fix Crashpad Building for CI Linux Target

- .github/workflows/ci-workflow.yml
- CMake/Helpers/CMakeMacOS.cmake
- CMake/Helpers/SetupFFMPEG.cmake
- CMakeLists.txt
- extern/CMakeLists.txt
- extern/sse2neon/CMakeLists.txt
- extern/sse2neon/README.txt
- extern/sse2neon/sse2neon/LICENSE
- extern/sse2neon/sse2neon/README.md
- extern/sse2neon/sse2neon/sse2neon.h
- src/Etterna/MinaCalc/PatternModHelpers.h
- src/Etterna/Models/Misc/StageStats.cpp
- src/Etterna/Screen/Others/ScreenSelectMusic.cpp
Depends-on: #1298 , as without it Etterna can't be built for M1 macs.
TODO: The applications this CI generates are not signed or notarized, which will cause problems. (See: #1292 )
The next step is to automatically sign the applications made by this CI when we make a release.
> Automatically build Apple ARM builds in CI

- Themes/Til Death/BGAnimations/_PlayerInfo.lua
Made this for myself, but a few people in EO were interested in this when I posted it and it doesn't conflict with any current functionality, so I figured it'd be good to have in the theme.
Right click doesn't conflict with muting the song preview because that doesn't work in the player info section.
Does let you change your judge on the results screen which is kind of weird but probably doesn't matter.
> Add left/right click to raise/lower judge in Til Death

- .github/workflows/ci-workflow.yml
Hopefully,
Closes: #1186 
-- I haven't been able to find anyone willing to help verify my fix, unfortunately (I pinged like all six people that have been known to ever encounter this problem).
That said, I checked the disassembly of the generated binary and it looks good?
-- `___chkstk_darwin` is definitely not present :D
> Automatically create a build of Etterna compatible with OSX High Sierra

- Docs/Building.md
`openssl-static` doesn't exist anymore. The new name is `openssl-devel` now https://packages.fedoraproject.org/pkgs/openssl/openssl-devel/
> Build docs: openssl-static -> openssl-devel on Fedora

- src/Etterna/Screen/Others/ScreenDebugOverlay.cpp
ForceOffAfterUse used to keep the debug menu listening to input while visually closing it. Now it doesn't do that.
However, there's still a problem where after exiting out of the debug menu with it the next F3 input gets eaten, requiring two F3 inputs to open the menu again.  I tried fixing this tonight but wasn't able to. Up to you whether it's fine to merge it like this or if that should be figured out first
> Fix ForceOffAfterUse not disabling debug menu input

- CMake/Helpers/SetupFFMPEG.cmake
The specific error was
```
/Users/runner/work/etterna/etterna/main/build/ffmpeg_dl/ffmpeg-2.1.3-src/libavcodec/flvenc.c:96:23: error: incompatible function pointer types initializing 'int (*)(AVCodecContext *, AVPacket *, const AVFrame *, int *)' (aka 'int (*)(struct AVCodecContext *, struct AVPacket *, const struct AVFrame *, int *)') with an expression of type 'int (AVCodecContext *, AVPacket *, AVFrame *, int *)' (aka 'int (struct AVCodecContext *, struct AVPacket *, struct AVFrame *, int *)') [-Wincompatible-function-pointer-types]
.encode2        = ff_MPV_encode_picture,
^~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [libavcodec/flvenc.o] Error 1
```
when trying to build for aarch64 on the Sonoma Github M1 runner
I believe this ffmpeg warning was likely fixed a long, long time …
> Prevent FFMPEG build warning from causing compilation error

- src/RageUtil/Sound/RageSoundReader_SpeedChange.cpp
- src/RageUtil/Sound/RageSoundReader_SpeedChange.h
This turned out to be easier than I expected
The main thing is not letting the left and right channels get time stretched/squeezed independently, which you can do with [this nonsense](https://en.wikipedia.org/wiki/Joint_encoding#M/S_stereo_coding). Less obtusely you can think of it as doing the algorithm on the average of the left/right channels instead of each independently, and then applying the change it wanted to make to both channels. And actually you could do exactly that, but I don't, because it helps masks an annoying issue to do with the way uncorrelated audio mixes, which makes certain noisey songs sound fluttery
The algorithm this thing uses still has a more fundamental issue which is on uprates it will just straight up skip beats. There's really no good reason for this but I …
> Unsuck unpitch rates

- src/Core/Platform/Platform.cpp
- src/Core/Platform/Platform.hpp
- src/Core/Platform/PlatformMac.mm
- src/Core/Platform/PlatformUnix.cpp
- src/Core/Platform/PlatformWin.cpp
Currently implemented for macOS
Implementations are stubbed out for Unix and Windows Core platform
> Add and implement Core::setClipboardText

- src/Etterna/MinaCalc/Dependent/HD_PatternMods/WideRangeJJ.h
- src/Etterna/MinaCalc/SequencedBaseDiffCalc.h
- src/Etterna/MinaCalc/UlbuAcolytes.h
And the warnings
Basically MSBase was computed with 4k specific stuff even though nothing about it is 4k-ish. MSBase isn't used anywhere so I just rewrote it to n-key cause whatever. The results are the same before and after for 4k. Uses `hand_col_masks` to split stuff into hands
> MinaCalc: Fix that one debug assert

- Themes/Til Death/BGAnimations/ScreenEvaluation decorations/default.lua
RA/MA Ratio Toggler is an Etterna addon that allows the player to switch between MA/PA ratios and RA/MA ratios on the Til Death evaluation screen by pressing the Shift key. This addon allows for the player to easily have access to more information about their accuracy in greater detail.
The calculateRA function computes the RA/MA ratio, where RA stands for “Ridiculous Attack” and MA stands for “Marvelous Attack”. This ratio provides a more nuanced view of the player’s precision by comparing the number of extremely accurate hits to those that are still considered excellent.
The MAPARatioContainer displays performance ratios to the player, specifically the RA/MA ratio and the MA/PA ratio. It dynamically updates these ratios based on whether the Shift key is pressed or not.
[Addon forum …
> Add RA/MA Ratio Toggler to Til Death

- src/Etterna/Actor/Menus/MusicWheel.cpp
this was driving me up the wall. exactly as the title implies, this makes cancelling song search keep you on the song you were on and not send you back up to the first song in the pack
intended for til death, but bare-frames seems to also use this function, as it's also affected by the change
rebirth already had this feature, the change doesn't appear to cause any conflicts with it
> til death & bare frames - don't send you to the top of the pack when cancelling/exiting song search

- src/RageUtil/Sound/RageSoundReader_SpeedChange_Good.cpp
Could reproduce this after looking at the logs. You can see the logic flaw immediately by looking at the m_bDraining test immediately above the assert, it will always fail if the audio reaches END_OF_FILE (which never happens under normal conditions, I dunno why). I spent a bit of time forcing this to happen when I originally wrote it so I don't know how I did this
> RageSoundReader_SpeedChange_Good crashes fix

- src/Etterna/Globals/global.h
- src/Etterna/Models/Misc/EnumHelper.h
- src/Etterna/Models/Misc/Game.cpp
- src/Etterna/Singletons/InputMapper.cpp
- src/arch/MovieTexture/MovieTexture_Generic.cpp
When this codebase was originally written, there wasn't a built-in
cross-compiler way to add compile-time asserts, so the original
authors did something clever by forcing the compile-time
instantiation of a undefined template class if a precondition was
not met.
However, this produces a wall of insane template errors all wrapped
within macro expansions that is completely unintelligible if you
haven't seen it before.
Since C++11 we have static_assert for the same purpose, and can
produce nice diagnostic strings as an added bonus :)
> Replace unweildy COMPILE_ASSERT macro with static_assert
