etternagame/etterna

- Themes/Til Death/BGAnimations/ScreenNetSelectMusic decorations/default.lua
- Themes/Til Death/BGAnimations/ScreenNetSelectMusic decorations/wifeonline.lua
Properly update MSD label
Properly display and update banner and scores
> Couple of fixes for NetSelectMusic

- src/InputFilter.cpp
- src/arch/ArchHooks/ArchHooks.cpp
- src/arch/ArchHooks/ArchHooks.h
- src/arch/ArchHooks/ArchHooks_Win32.cpp
- src/arch/ArchHooks/ArchHooks_Win32.h
Should not break anything on Linux, requires testing.
> Fix mouse position when resized window on windows

- CMake/SetupFfmpeg.cmake
Works(Thanks to @despoa in https://github.com/etternagame/etterna/pull/38 using --disable-izma)
> Fix linux build

- Themes/Til Death/BGAnimations/_mouseselect.lua
- Themes/Til Death/BGAnimations/_mousewheelscroll.lua
- src/RoomWheel.cpp
- src/ScreenNetRoom.cpp
- src/ScreenNetSelectMusic.cpp
Without this double clicking the current song crashes(And sometimes the song could be changed after selecting it)
> Fix mouse inputs after song select

- src/ScreenStatsOverlay.cpp
- src/ScreenStatsOverlay.h
how is this guys, here is an example
> Added background quad to ScreenStatsOverlay for FPS/AV FPS and VPS

- Themes/Til Death/BGAnimations/ScreenNetRoom decorations/profile.lua
- Themes/Til Death/BGAnimations/ScreenNetRoom decorations/roomsearch.lua
- Themes/Til Death/BGAnimations/ScreenNetRoom decorations/tabs.lua
- src/MusicWheel.cpp
- src/MusicWheel.h
- src/WheelBase.cpp
- src/WheelBase.h
Change the wheelbase and musicwheel load method signature to use string instead of rstring
> Fix roomwheel

- Themes/Til Death/BGAnimations/ScreenSelectMusic decorations/goaltracker.lua
Fixes https://github.com/etternagame/etterna/issues/80
> Make current goal page specific to each filter

- src/Player.cpp
Should fix these 2 issues:
https://github.com/etternagame/etterna/issues/73
https://github.com/etternagame/etterna/issues/90
> Fix a couple lua interface things with CCoff and judgement msgcommand

- src/DownloadManager.cpp
This should heavily reduce download lag.
> Dont sleep while downloading

- Themes/Til Death/Scripts/02 ThemePrefs.lua
> Fix the saved value for the FullProgressBar Y

- Docs/Themerdocs/Examples/Example_Actors/ActorFrameTexture.lua
- Docs/Themerdocs/Examples/Example_Actors/ActorScroller.lua
- Docs/Themerdocs/Examples/Example_Screens/ScreenHeartEntry.lua
- Docs/Themerdocs/Examples/Example_Screens/ScreenMapControllers.lua
- Docs/steps.lua
- NoteSkins/common/common/Fallback Explosion.lua
- Themes/_fallback/Scripts/03 Gameplay.lua
Should fix common (default) noteskin errors
> Run cmd lua python script replacer on root folder

- Themes/Til Death/BGAnimations/_halppls.lua
added many keyboard shortcuts to the help menu
> Improved F12 Help Menu

- Themes/Til Death/BGAnimations/ScreenGameplay overlay/WifeJudgmentSpotting.lua
> Fix the check for enabled error bar

- src/ImageCache.cpp
- src/SongCacheIndex.cpp
here we go, code to fix the imagecache so it doesnt generate every time, it should also remove most dependency on songcache
> Fixing imagecache

- Themes/Til Death/BGAnimations/ScreenSelectMusic decorations/filters.lua
I threw in another minor change that also fixes a case where if you click Reset you can't use the numbers to change tabs.
This code is mostly Nick's.
> Fix Filter Lag & Filter Tab Change Lock

- README.md
Updated URL for Bug Reporting in README.md and deleted old duplicate for BugReporting.md in main folder.
> Update README.md and delete duplicate BugReporting.md

- Contributing.md
More text cleanup and formatting.
> Update Contributing.md (again)

- Themes/Til Death/BGAnimations/ScreenGameplay overlay/WifeJudgmentSpotting.lua
- Themes/Til Death/BGAnimations/ScreenGameplay overlay/npscalc.lua
- Themes/Til Death/BGAnimations/ScreenGameplay underlay/ScreenFilter.lua
- Themes/Til Death/Graphics/Player combo/default.lua
- Themes/Til Death/Graphics/Player judgment/default.lua
> Clean up the customize gameplay code

- Themes/_fallback/metrics.ini
- src/ArrowEffects.cpp
Added a option in metrics.ini to disable flash (or glow in other words) when playing with hidden or sudden mod. Added a under-construction country ranking.
>  Added a option "NoGlow" in metrics.ini.

- src/Song.cpp
- src/SongManager.cpp
These crash because the web that is this codebase gets tangled when we try it multithreaded-ly
> Remove song load checkpoints

- src/RageDisplay_GLES2.cpp
- src/RageDisplay_GLES2.h
This PR fixes the build on Linux by changing some mismatched types
> Fix build on Linux

- Themes/Til Death/BGAnimations/ScreenGameplay overlay/WifeJudgmentSpotting.lua
- Themes/Til Death/BGAnimations/ScreenGameplay overlay/messagebox.lua
- Themes/Til Death/Scripts/01 player_config.lua
- Themes/Til Death/Scripts/02 CustomizeGameplay.lua
- src/ActorFrame.cpp
Includes x, y, width, height and rotation(!!).
> Add customization to the lifebar

- src/ScreenInstallOverlay.cpp
- src/SongManager.h
Add pack banners to the cache generator (Via command line flag) used by EO
> Eocachepackbanner

- src/Player.cpp
- src/Player.h
> Fix bug involving incorrectly tapping notes too early while still inside holds and rolls

- Themes/Til Death/BGAnimations/ScreenSelectMusic decorations/wifeTwirl.lua
- src/ActorSound.cpp
- src/ActorSound.h
- src/GameSoundManager.cpp
- src/GameSoundManager.h
- src/NoteField.cpp
- src/RageSound.cpp
- src/RageSound.h
- src/Screen.cpp
- src/Screen.h
- src/ScreenSelectMusic.cpp
- src/arch/Sound/RageSoundDriver_Generic_Software.cpp
probably, it's a lot better
they still happen
> Largely reduce deadlock crashes with preview and visualizer

- src/Etterna/Singletons/SongManager.cpp
So we don't get kicked while diff reloading (And respond to ping pong messages)
> Update/Poll NSMAN while diff. reloading

- Themes/Til Death/BGAnimations/MPscoreboard.lua
- src/Etterna/Screen/Network/ScreenNetEvaluation.cpp
Should fix https://github.com/etternagame/etterna/issues/462
> Multiplayer scoreboard improvements

- src/archutils/Win32/Crash.cpp
On Windows, every thread has a separate stack space. It is possible to create a separate thread to do the exception handling job without having to mess with the stack pointer. Therefore we can happily remove any inline assembly.
Special thanks to [sigatrev](https://github.com/sigatrev) for inspiration.
> Windows CrashHandler: Create a thread for separate stack

- src/RageUtil/Utils/RageUtil.cpp
- src/RageUtil/Utils/RageUtil.h
> Rewrite RageUtil's ssprintf to Fix Occasional Stack Overflow Crash

- .travis.yml
openssl suddenly cant be found
lets try to find it
> Fix Mac Travis Builds

- src/Etterna/Models/Misc/AdjustSync.cpp
- src/Etterna/Models/Misc/AdjustSync.h
- src/Etterna/Models/Songs/SongOptions.cpp
- src/Etterna/Models/Songs/SongOptions.h
- src/Etterna/Screen/Gameplay/ScreenGameplay.cpp
- src/Etterna/Screen/Others/ScreenDebugOverlay.cpp
- src/Etterna/Screen/Others/ScreenSyncOverlay.cpp
this kind of invalidates charts and isnt practical, really
it would be better to use a third party program to make bpm adjustments
> Remove Autosync Tempo & Manual Tempo Adjustments

- src/arch/ArchHooks/ArchHooks_Win32.cpp
This code has been here for 13 years. The comment for 10. People are experiencing crashes here and we can't really figure out why. This should be a first step in figuring out why.
> Make Win32 Invalid Parameter Handler more informative

- Themes/_fallback/BGAnimations/ScreenSystemLayer overlay/default.lua
- Themes/_fallback/Graphics/Player judgment/default.lua
- Themes/_fallback/metrics.ini
Starting to find little holes that cause newer themes to fail in various ways for no good reason. Need to fix these and also clean up other stuff where we can.
> Fix some broken fallback theme Lua

- Themes/Til Death/BGAnimations/_calcdisplay.lua
- src/Etterna/Globals/MinaCalc.cpp
- src/Etterna/Globals/MinaCalc.h
- src/Etterna/Globals/SoloCalc.cpp
- src/Etterna/Models/Misc/GameConstantsAndTypes.cpp
- src/Etterna/Models/Misc/PlayerStageStats.cpp
- src/Etterna/Models/Misc/StageStats.cpp
- src/Etterna/Models/NoteData/NoteDataStructures.h
- src/Etterna/Models/StepsAndStyles/Steps.cpp
- src/Etterna/Singletons/ScoreManager.cpp
added ix's SoloCalc
updated CMakeLists for SoloCalc
wifeTwirl and Steps updated to allow MSD display for solo StepsType
did clang format/tidy on sources and headers
> Add SoloCalc

- Themes/Til Death/BGAnimations/ScreenEvaluation decorations/default.lua
- Themes/Til Death/BGAnimations/ScreenNetEvaluation decorations.lua
- Themes/Til Death/BGAnimations/ScreenSelectMusic decorations/default.lua
- Themes/Til Death/BGAnimations/ScreenSelectMusic decorations/score.lua
- Themes/Til Death/BGAnimations/ScreenSelectMusic decorations/wifeTwirl.lua
- Themes/Til Death/BGAnimations/_PlayerInfo.lua
- Themes/Til Death/BGAnimations/_calcdisplay.lua
- Themes/Til Death/BGAnimations/offsetplot.lua
- Themes/Til Death/metrics.ini
- Themes/_fallback/Scripts/10 Scores.lua
- src/Etterna/Actor/Gameplay/Player.cpp
- src/Etterna/Globals/MinaCalcOld.cpp
- src/Etterna/Models/Misc/HighScore.cpp
- src/Etterna/Models/Misc/HighScore.h
- src/Etterna/Models/Misc/PlayerAI.cpp
- src/Etterna/Models/Misc/PlayerStageStats.cpp
- src/Etterna/Models/Misc/StageStats.cpp
- src/Etterna/Models/NoteData/NoteData.cpp
- src/Etterna/Models/NoteData/NoteData.h
- src/Etterna/Models/NoteLoaders/NotesLoaderSM.cpp
- src/Etterna/Models/StepsAndStyles/Steps.cpp
- src/Etterna/Screen/Others/ScreenInstallOverlay.cpp
- src/Etterna/Screen/Others/ScreenSelectMusic.cpp
- src/Etterna/Singletons/DownloadManager.cpp
- src/Etterna/Singletons/GameState.h
- src/Etterna/Singletons/ScoreManager.cpp
- src/Etterna/Singletons/ScoreManager.h
- src/Etterna/Singletons/SongManager.cpp
- src/RageUtil/Utils/RageUtil.h
test version that sands off the rough edges in preparation for release version
everything is rerouted to old calc
> Wife 3 release prep

- src/Etterna/Globals/MinaCalc.cpp
This was something Mina suggested and I attempted to do
> Splitting metanoteinfo into metanoteinfo and intervalinfo

- CMake/Helpers/CMakeWindows.cmake
- src/Etterna/Globals/MinaCalc.cpp
im more clear on STUFF now
- stuff that operates independent of hands tends to need metadata generated across all columns by noterow, and use basic interval info
- most hand dependent stuff needs a small mount of basic info and a large amount of meta info, and has shifted towards sequencing
- these are not necessarily mutually exclusive sets of data but they share little overlap other than their initial derivation point (noteinfo) and should be run in separate passes
> major calc data structure refactoring

- src/archutils/Darwin/JoystickDevice.cpp
- src/archutils/Darwin/MouseDevice.cpp
- src/archutils/Unix/Backtrace.cpp
Boring changes to make MacOS compile on the latest develop.
(several min/max calls had to be changed into fmin/fmax and a file was missing an <algorithm> include)
> Fix mac os compile

- .gitignore
- Fix patterns that ignored too much (e.g. the pattern "Songs/" would match and
ignore the entire subdirectory "src/Etterna/Models/Songs")
- Add the other Etterna binary names (e.g. "Etterna-RelWithDebInfo") to
be ignored
> .gitignore improvements and fixes

- Docs/legacy/Luadoc/Lua.xml
- Themes/Til Death/BGAnimations/ScreenSelectMusic decorations/tags.lua
- Themes/Til Death/Languages/en.ini
- Themes/Til Death/Languages/zh.ini
- src/Etterna/Actor/Menus/MusicWheel.cpp
- src/Etterna/Actor/Menus/MusicWheel.h
Also adds all the GUI associated with the change to standard theme, maintains previous lua function 'FilterByStepKeys' functionality
> Implement ability to exclude songs based on tags

- src/RageUtil/Sound/RageSound.h
> Fix muFFT-related issue stopping compilation on MSVC Debug Target

- src/RageUtil/Graphics/RageDisplay_OGL.cpp
Credits to poco0317 for finding the commit which broke it
That commit seems to have broken creation of textures without
initializing them which is done for the background movie texture
> Fix issue #914

- README.md
This is unlikely as-is to change between releases, so it doesn't make sense
to copy it verbatim every single release while having inaccurate info visible.
> Update README.md to include MacOS installation procedure

- .github/ISSUE_TEMPLATE/feature_request.md
We currently only have a bug-report template, which is non-ideal.
This template helps show people making feature requests what details should be present.
It also automatically tags issues made through the template with the label "Enhancement".
> Add new feature request issue template

- src/Etterna/Singletons/InputFilter.cpp
- src/Etterna/Singletons/InputFilter.h
- src/arch/InputHandler/InputHandler.cpp
Closes #978
Note: Tested on macOS, seems to work great.
I'd really appreciate if someone could test this for Windows and Linux.
> Add support for CAPSLOCK key modifying text fields when enabled

- src/arch/Sound/RageSoundDriver_AU.cpp
Tested on Big Sur, Mojave
I'm going to leave this as a draft until Hidden confirms it works.
Closes #1015
> Replace deprecated audio API usage to make sound work on Big Sur

- Themes/Til Death/BGAnimations/ScreenSelectMusic decorations/playlists.lua
- Themes/Til Death/BGAnimations/ScreenSelectMusic decorations/profile.lua
- Themes/Til Death/BGAnimations/ScreenTextEntry underlay.lua
- Themes/Til Death/BGAnimations/_PlayerInfo.lua
> themestuff 1.01

- CMake/Helpers/SetupFFMPEG.cmake
Probably shouldn't be pulling this from Stepmania.
> Change FFMPEG Upstream To Etterna Fork

- src/Core/Platform/Platform.cpp
- src/Core/Platform/Platform.hpp
- src/Core/Platform/PlatformMac.mm
- src/Core/Platform/PlatformUnix.cpp
- src/Core/Platform/PlatformWin.cpp
- src/Etterna/Singletons/DownloadManager.cpp
flashWindow doesn't actually flash the window on macOS.
requestUserAttention seems like a nicer platform-agnostic name for the function
> Rename flashWindow to requestUserAttention, and implement for macOS

- src/Etterna/Actor/Menus/DifficultyList.cpp
- src/Etterna/Actor/Menus/DifficultyList.h
See: https://github.com/etternagame/etterna/pull/1079
I made the vector contain unique_ptr's so the addrs should remain stable. Ran into a bunch of compiler errors because having a unique_ptr as a field apparently deletes that class's move/copy constructors? Had to do a whole sing and dance with a dummy struct implementing those manually. Someone more well-versed in C++ can probably do this without that, but I don't want to deal with C++ errors any more today.
> Fix bug poco found v2

- src/Core/Platform/PlatformWin.cpp
Fixes https://github.com/etternagame/etterna/issues/1087
See comments in the commit and discussion in https://github.com/etternagame/etterna/issues/1087
> Fix multiple instance bug

- Themes/Rebirth/BGAnimations/ScreenEvaluation decorations/mainDisplay.lua
- Themes/Rebirth/BGAnimations/ScreenGameplay overlay/elements/_gameplayelements.lua
- Themes/Rebirth/BGAnimations/ScreenSelectMusic overlay/default.lua
- Themes/Rebirth/Scripts/98 util.lua
- Themes/Til Death/BGAnimations/ScreenEvaluation decorations/default.lua
- Themes/Til Death/BGAnimations/ScreenGameplay overlay/WifeJudgmentSpotting.lua
- Themes/Til Death/BGAnimations/ScreenSelectMusic overlay/default.lua
Reorganized til death calls and added missing rebirth calls
> Update discord presence calls for rebirth and til death

- src/RageUtil/Sound/RageSound.cpp
This should fix https://crash.etterna.dev/crash-reports/2af49c0d-c8a0-4fe7-932b-592cdd9c6947
The decode thread could block in RageSound::GetDataToPlay waitin for
the recent samples mutex, and then the music thread in GameSoundManager
could delete the RageSound, which also locks the mutex.
If the deleting thread locked it first, and the decode thread waited for
it, it deleted the fft Plan and then the decode thread tried to use it.
Calling Unload() before deleting the plan should guarantee that the
decode thread no longer tries to use that RageSound. Unload() locks g_Mutex
which the GameSoundManager thread locks before deleting the RageSound.
> Fix multithreaded bug in RageSound 

- src/Etterna/Actor/Menus/OptionsList.cpp
- src/Etterna/MinaCalc/MinaCalc.cpp
- src/Etterna/Models/Misc/Difficulty.h
- src/Etterna/Models/Misc/OptionRowHandler.cpp
- src/Etterna/Singletons/NetworkSyncManager.cpp
- src/Etterna/Singletons/ScoreManager.cpp
- src/Etterna/Singletons/SongManager.cpp
- src/arch/Dialog/DialogDriver_Win32.cpp
- src/arch/InputHandler/InputHandler_Win32_MIDI.cpp
- src/arch/LoadingWindow/LoadingWindow_Win32.cpp
- src/archutils/Win32/GraphicsWindow.cpp
- src/archutils/Win32/arch_setup.h
On MSVC from VS2022 version 19.30.30709
The only warnings that remain are in /extern (discord-rpc, rapidjson, glew)
> Fix remaining MSVC warnings

- src/arch/MovieTexture/MovieTexture_FFMpeg.cpp
Fixes #1155
I tested this with 2 movies on screen at once to make sure I didn't break it for more than 1 movie at the same time by adding a second banner with a previous song to the TD selectmusic screen in wifetwirl.lua
<details>
<summary>Lua snippet</summary>
```lua
local prevSong = nil
t[#t + 1] = Def.Sprite {
Name = "Banner2",
InitCommand = function(self)
self:x(120):y(121):halign(0):valign(0)
self:scaletoclipped(capWideScale(get43size(384), 384), capWideScale(get43size(120), 120)):diffusealpha(1)
end,
MintyFreshCommand = function(self)
if INPUTFILTER:IsBeingPressed("tab") then
self:finishtweening():smooth(0.25):diffusealpha(0):sleep(0.2):queuecommand("ModifyBanner")
else
self:finishtweening():queuecommand("ModifyBanner")
end
end,
ModifyBannerCommand = function(self) …
```
> Fix file leak in MovieTexture_FFMpeg.cpp

- extern/discord-rpc/src/serialization.h
- src/Etterna/Singletons/NetworkSyncManager.h
Also use forward declarations in nsman's header
> Silence rapidjson warning on msvc

- Themes/Til Death/BGAnimations/ScreenSelectMusic overlay/currentsort.lua
- Themes/_fallback/Languages/en.ini
- Themes/_fallback/metrics.ini
- src/Etterna/Actor/Menus/MusicWheel.cpp
- src/Etterna/Models/Misc/GameConstantsAndTypes.cpp
- src/Etterna/Models/Misc/GameConstantsAndTypes.h
- src/Etterna/Models/Songs/Song.cpp
- src/Etterna/Models/Songs/Song.h
- src/Etterna/Models/Songs/SongUtil.cpp
- src/Etterna/Models/Songs/SongUtil.h
Added new SortMode "StepAuthor" for Issue#1244. This sort mode uses the title as a secondary metric to sort under.
> Added new SortMode "StepAuthor" for Issue#1244

- Themes/Til Death/Graphics/Player judgment/default.lua
effectcolor -> effectcolor1
funny error. already fixed in rebirth
> til death judge tween fix

- src/Etterna/MinaCalc/MinaCalc.cpp
makes my development a little easier
> Move testing behind another compiler flag for now

- .gitignore
- Themes/Til Death/BGAnimations/ScreenEvaluation decorations/MPscoreboard.lua
- Themes/Til Death/BGAnimations/ScreenEvaluation decorations/scoreboard.lua
- src/Etterna/Models/HighScore/HighScore.cpp
The reason for the first commit is that CMake with Visual Studio creates /out/ directory automatically by default and puts all the build garbage there
> gitignore improvement + changing judge dividers for better readibility with custom fonts
